// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zomzmyfpjhspsopzmrgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvbXpteWZwamhzcHNvcHptcmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODk0MDksImV4cCI6MjA2OTc2NTQwOX0.BdjpuBWqEcxvUbvxUjvyVVtzdLwH2tYn6d1nUygPiBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});